name: axiom-sdk-client rust tests

on:
  push: 
    paths:
      - "rust"

jobs:
  axiom-sdk-rust-client:
    runs-on: ubuntu-latest-64core-256ram
    steps:
      - uses: actions/checkout@v3
      - name: Build rust client
        run: |
          cargo build --verbose
      - name: Test rust client
        run: |
            export PROVIDER_URI=${{ secrets.PROVIDER_URI_GOERLI }}
            cargo test
      