name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  axiom-sdk-rust-client:
    runs-on: ubuntu-latest-64core-256ram
    steps:
      - uses: actions/checkout@v3
      - name: Build rust client
        run: |
          cargo build --verbose
      - name: Install KZG params
        run: |
          for k in {5..21}
          do
            wget "https://axiom-crypto.s3.amazonaws.com/challenge_0078/kzg_bn254_${k}.srs"
          done
          mv *.srs params/
      - name: Test rust client
        run: |
          export PROVIDER_URI=${{ secrets.PROVIDER_URI_SEPOLIA }}
          cargo test
